baseURL = "https://kxsumi.github.io/megathread/"
languageCode = "en-us"
title = "r/Piracy Megathread"
theme = "hextra"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Documentation"
    pageRef = "/docs"
    weight = 1
  
  [[menu.main]]
    name = "Guides"
    pageRef = "/docs/guides"
    weight = 2
  

[params]
  description = "The complete piracy megathread - your guide to safe and reliable piracy resources"
  
  [params.navbar]
    displayTitle = true
    displayLogo = false
  
  [params.footer]
    displayCopyright = true
    displayPoweredBy = false

  [params.search]
    enable = true
    type = "flexsearch"

  [params.editURL]
    enable = false